### ISSUE TITLE
missing autoblacklist option for PIDeviceInfo

### ISSUE THREAD

**Issue by bergerr2** [presence-insights/pi-clientsdk-android#11]
There is no way to set the autoblacklist property for a device.

**Comment by CiaranHannigan** [comment]
autoblacklist will not be settable by the SDK. This is a value that will be triggered by PI on the backend.

However, this value should be added to the PIDevice doctype class.

**Comment by CiaranHannigan** [comment]
https://github.com/presence-insights/pi-clientsdk-android/pull/16
