### ISSUE TITLE
SDK should not send enter events when rebooting the device while in a geofence

### ISSUE THREAD

**Issue by JulienCarnec** [presence-insights/pi-clientsdk-android#26]
Scenario:
- the user enters a geofence
- an enter event is posted
- the user reboots the phone without leaving the geofence
- after reboot, as the phone is still in the same geofence, a new enter event is posted, and it should not, because the connector sees 2 consecutive enter events.

**Comment by lolo4j** [comment]
This happens at [this line](https://github.com/presence-insights/pi-clientsdk-android/blob/89855_dev_outdoor/pi-geofence/src/main/java/com/ibm/pi/geofence/PIGeofencingService.java#L510). In case of a reboot event we should not specify `INITIAL_TRIGGER_ENTER` for geofences the user is already in. Therefore the `GeofencingRequest` shall need to be split into multiple requests, some wtih `INITIAL_TRIGGER_ENTER` and some without.

**Comment by lolo4j** [comment]
fixed
