### ISSUE TITLE
Cannot retrieve mac address in Android 6

### ISSUE THREAD

**Issue by mbillau** [presence-insights/pi-clientsdk-android#8]
See this: https://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-hardware-id

The mac address can no longer be received programmatically. We currently use the mac address to uniquely identify the id: https://github.com/presence-insights/pi-clientsdk-android/blob/master/app/src/main/java/com/ibm/pisdk/PIDeviceID.java#L77

**Comment by bergerr2** [comment]
We might be ale to use the Android_ID, the only downside being that it may be changed on a factory reset: https://developer.android.com/reference/android/provider/Settings.Secure.html#ANDROID_ID

**Comment by CiaranHannigan** [comment]
Yes this was recommended to me as well from Dillon. I feel like it should be the route we take. Don't think we need to worry about that extreme edge case of a factory reset right now. 

Apparently it is recommended to avoid using HW IDs like `ANDROID_ID`. I think we should review this link, http://developer.android.com/training/articles/user-data-ids.html, and determine a better solution.

**Comment by drcariel** [comment]
As an alternative, the Bluemix Push Notifications service assigns a unique deviceId upon registration and persists after uninstall/re-install as long as you are using the same Push and GCM project backend. I have confirmed this on both Marshmallow and previous versions.

**Comment by CiaranHannigan** [comment]
Interesting. What does the app use during registration of the device? the `ANDROID_ID`?

**Comment by CiaranHannigan** [comment]
https://github.com/presence-insights/pi-clientsdk-android/pull/14
